import type { Metadata } from 'next';
import '@/styles/globals.css';
import { cn } from '@/lib/utils';
import { fontMono, fontSans } from '@/lib/fonts';
import { Toaster } from '@/components/atoms/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: '/favicon.ico',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn(fontSans.className, fontMono.className)}>
        {children}
        <Toaster position='top-right' richColors />
      </body>
    </html>
  );
}
